---
creation_rules:
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age18s03lpurvy4ce2qjfc0u7yk4lfxw4n5h0hz9gpyp99zjdq5j84cs00rksh
      age1c9vfq2ql6e8j034hhhfu4yz7tt9zxdgu6xms385vn3le5agztq2smsvs8u