apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secrets
    namespace: cert-manager
stringData:
    access-key-id: ENC[AES256_GCM,data:hyNMIDJ4bPwSXWzqaAMZGj5099A=,iv:Isoin5Fpny2jMO5Ew3W+8ayiH/uzdc/oIj3EYaz5xZY=,tag:kXUsSdo0xpF6i63Sbi8hrw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Yj8IUoPQ2ibzYLdk6yQyvlSx+NdqBTbqyj7YJcbPOw6KYEGB/9aUOw==,iv:BM25JI/ccDTQCtDgu9NGBxnMXBeDfX76PJywdvIWLCg=,tag:G1kg1y1QVQhovKHVIgvkaw==,type:str]
    dns-zones:
        - ENC[AES256_GCM,data:ZzVctDO/KOBzX0q8NIsXdg==,iv:Nyo1LffefcJJ0JXU06hbZM3BqtaoPQvnOh5NwoAyNxY=,tag:R4TP4md1EMQ78qXtZut2RQ==,type:str]
        - ENC[AES256_GCM,data:mklNg5eQBIYLq1VYcqUpxcM=,iv:FI/vu982fLaNLkrcJhuQZZRNo1a20fP6RaCjlvxT72g=,tag:EI+crROjnOg7CTKk2YpdZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18s03lpurvy4ce2qjfc0u7yk4lfxw4n5h0hz9gpyp99zjdq5j84cs00rksh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0lrT0R5RFlUZWFNejJ5
            bWZLVVFqSHYvZCtxM3Zyako4amQzam0ybFVFCkVLZCs3RnZwUHFLWWRSM1hYcSsw
            MmNEaEdYeEI4N2t6UUxFdUI4bHZFYkUKLS0tIGVQWnJYcW5UTllDQkZ0ckR1ZVJH
            bEcxalo5bURRTktldCtCYUh3MGhkNzAKqTGvgZvfXhvS+Ei1uIWP3kY8iMs12RZU
            8SGHY76u4+cFiQKWx4tZLErNrSR9hOrLZxy3BCsSUlzCBuLDua1Pzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c9vfq2ql6e8j034hhhfu4yz7tt9zxdgu6xms385vn3le5agztq2smsvs8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS0lIcytMeDd0eFJsV2o5
            VlR5SlhsckdLSlJtRVRuTSttd3doeVEvRGhnClZ3emxMWW9iaE8xWDhxb0R0bDRB
            N3hQYU9qU09ZSGo3L01ydUdlbHFLU1UKLS0tIHRuaUEySEg1cGZMZnhBWm9DOE1W
            bmt0WGE2dmhPOXpjOW1jTFFrRUlUVVEK5W7ahIBRCCnxlsaeQn3FkFe8CWN9kb49
            Iieyg2lM8FrgLn5O2uU6OxLB/FmFxAwz0dTWM3vsiCpdy9b4IoO0Mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ1BCWUoramowZjhRQW9q
            cFJ6MElid0x5ZDZ3TEplU2ZiMjhKTUdYZGhzCnlyRDBVMVZ4Si9lRVVMVHZCWm1q
            U1k5R3N3TTI3TGlzR3l1ZFF6akxJVWcKLS0tIGJtazlFUkJBZWtHN2NjZkNialRI
            enBzT3ZQV2lFOEFXUS84N1FFdU5uSGMKk7yUsBJSXNguA33c1Vc2xFFJzJhBE+RD
            RZFXHmD6j6SMqQ1SgXX/d9snAcp2otd8C1emaKwVKfs34A1ldWAxcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T18:39:47Z"
    mac: ENC[AES256_GCM,data:yZ6kcJGcMEsi1I9OLIxEBL8J3MUKe+Lv8OCeeHktmACSmwRWIU5K4HZnkJODGGKc5nKo5Ul4UI4fK48hBq/1HBejBzg+WD8D2K+5hEzGbwnWaJjqLBXO4Q7nr16f1zYewoQF3FHDPwk9wS10YbLQvPFTGwxAVSygKrpTeZCW1Fs=,iv:u324tb1iCiA3FlXhJlZ1B1OfmdQJqMMaLNOXpvggulU=,tag:hQPtSvbnDKw83lW8Z2RwEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
