---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: "Europe/London"
      service:
        #externalIPs:
        #  - "${SVC_NGINX_ADDR}"
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: |-
          401,403,404,500,501,502,503
        enable-brotli: "true"
        #forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      #podAnnotations:
        #configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          memory: 1000Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.15.0
      replicaCount: 3
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ghost
        - name: SHOW_DETAILS
          value: "false"